version: '3.8'

services:
  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pintrader
    volumes:
      - ./frontend:/app
    depends_on:
      - db
    networks:
      - pintrader-net
    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pintrader
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pintrader-net

networks:
  pintrader-net:
    driver: bridge

volumes:
  postgres_data:
